import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import { Toaster } from "sonner";
import { cookies } from "next/headers";
import { verifyToken } from "@/helpers/jwt";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStorage = await cookies();
  const token = cookieStorage.get("token")?.value;

  let userId: string | null = null;

  if (token) {
    const decoded = verifyToken(token) as { _id: string };
    userId = decoded._id;
  }

  return (
    <html lang="en">
      <body>
        {token ? <Navbar userToken={token} userId={userId} /> : <Navbar />}
        <main>{children}</main>
        <Toaster richColors position="top-center" />
      </body>
    </html>
  );
}
